#host: vm3
- name: "Master Playbook 3: VM3"
  hosts: Vm3          # specified in the MyInventory file
  remote_user:  cc      # note that the user is ubuntu for
                             # vagrant-created VM else use the
                             # appropriate user name
  become: true

  tasks:    # the task to be performed (here I am showing the effect of include_)
  #- include_tasks: tasks/playbook_exec_app_on_cloud_vm.yaml
  - include_tasks: tasks/playbook_VM3.yml