---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
    - name: couchdb
      port: 30009
    - name: kafka
      port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template: 
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: parishwolfe/cloud_class:latest
          ports:
            - containerPort: 9092
            - containerPort: 5984
            - containerPort: 30009
          env:
            - name: KAFKA0
              value: 129.114.26.158:30008
            - name: KAFKA1
              value: 129.114.26.158:30007
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: password
            - name: COUCHDB_HOST
              value: 129.114.26.158

