---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
      name: client
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless-service
spec:
  selector:
    app: zookeeper
  clusterIP: None # headless service
  ports:
    - protocol: TCP
      port: 2888
      targetPort: 2888
      name: server
    - protocol: TCP
      port: 3888
      targetPort: 3888
      name: leader-election

# END

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-internal
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: broker0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-external
spec:
  type: NodePort
  selector:
    app: kafka
    brokerId: "0"
  ports:
    - name: bootstrap
      protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 30985

### END ###
