---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  # labels:
  #   app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: zookeeper-host
      containers:
      - name: zookeeper
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
        #   name: client
        - containerPort: 2888
        #   name: server
        - containerPort: 3888
        #   name: leader-election
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "0.5"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "0.6"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-b0-deployment
  labels:
    app: kafka0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka0
      #brokerId: "0"
  template:
    metadata:
      labels:
        app: kafka0
        #brokerId: "0"
    spec:
      # Wait for zookeeper to start up first
      initContainers:
      - name: wait
        image: alpine
        command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 zookeeper-service 2181 && exit 0 || sleep 3; done; exit 1"]
      containers:
      # Kafka Broker 0
      - name: broker0
        image: bitnami/kafka
        ports:
        - containerPort: 9092
          name: internal
        - containerPort: 9093
          name: external
        - containerPort: 9094
          name: interbroker
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        #   value: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERBROKER_LISTENER"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://129.114.26.158:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
#         resources:
#           requests:
#               memory: "256Mi"
#               cpu: "0.5"
#           limits:
#             memory: "512Mi"
#             cpu: "0.6"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-b1-deployment
  labels:
    app: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
      #brokerId: "1"
  template:
    metadata:
      labels:
        app: kafka1
        #brokerId: "1"
    spec:
      initContainers:
      - name: wait
        image: alpine
        command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 zookeeper-service 2181 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: broker1
        image: bitnami/kafka
        ports:
        - containerPort: 9092
          name: internal
        - containerPort: 9093
          name: external
        - containerPort: 9094
          name: interbroker
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        #   value: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERBROKER_LISTENER"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://129.114.26.158:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        # resources:
        #   requests:
        #       memory: "256Mi"
        #       cpu: "0.5"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "0.6"

### END  ###
