
- name: Start couchdb pod
  command:
    cmd: kubectl apply -f ~/5287-A2/Ansible_Kubernetes/couchdb_files/couchdb.yaml

- name: Start services kafka, zookeeper
  command:
    cmd: kubectl apply -f ~/5287-A2/Ansible_Kubernetes/kafka_files/kafka_service.yaml

- name: Create deployments kafka, zookeeper
  command:
    cmd: kubectl apply -f ~/5287-A2/Ansible_Kubernetes/kafka_files/kafka_deployment.yaml

- name: create consumer pod
  command:
    cmd: ~/5287-A2/Ansible_Kubernetes/code_files/kubectl apply -f consumer.yaml
