
- name: Start couchdb pod
  command:
    chdir: "~/5287-A2/Ansible_Kubernetes/couchdb_files/"
    cmd: kubectl apply -f couchdb.yaml

- name: Start services kafka, zookeeper
  command:
    chdir: "~/5287-A2/Ansible_Kubernetes/code_files/"
    cmd: kubectl apply -f test-service.yaml

- name: Create deployments kafka, zookeeper
  command:
    chdir: "~/5287-A2/Ansible_Kubernetes/code_files/"
    cmd: kubectl apply -f test-kafka-zoo.yaml



