---

- name: install prerequisites
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
      - net-tools
      - jq
    update_cache: yes
    state: present

- name: configure firewall
  become: yes
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "22"
    - "80"
    - "443"
    - "2379"
    - "2380"
    - "4040"
    - "5000"
    - "6443"
    - "7076"
    - "7077"
    - "7078"
    - "7079"
    - "8001"
    - "8080"
    - "8081"
    - "8472"
    - "8285"
    - "30000"
    - "30001"
    - "30002"
    - "30003"
    - "30004"
    - "30005"
    - "30006"
    - "30007"
    - "30008"
    - "30009"
    - "30010"
    - "10252"
    - "10251"
    - "10250"

- name: Clone github to get access to files
  ignore_errors: yes
  git:
    repo: https://github.com/parishwolfe/5287-A2.git
    dest: /home/cc/5287-A2
    clone: yes
    update: yes

- name: make install sources script executable
  become: yes
  file: dest=/home/cc/5287-A2/Ansible_Kubernetes/kubernetes_files/update_sources.sh mode=a+x

- name: run install sources script
  become: yes
  command: sh /home/cc/5287-A2/Ansible_Kubernetes/kubernetes_files/update_sources.sh

- name: install docker
  become: yes
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present

- name: swap off
  become: yes
  command: swapoff -a

- name: update docker config
  become: yes
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
    line: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd

- name: restart docker
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: install kubernetes
  become: yes
  apt:
    pkg:
      - kubeadm
      - kubelet
      - kubectl
      - kubernetes-cni
    update_cache: yes
    state: present

...