---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
      name: zookeeper-communication
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: zookeeper-headless-service
# spec:
#   selector:
#     app: zookeeper
#   clusterIP: None # headless service
#   ports:
#     - protocol: TCP
#       port: 2888
#       targetPort: 2888
#       name: server
#     - protocol: TCP
#       port: 3888
#       targetPort: 3888
#       name: leader-election

# END

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-service-internal
# spec:
#   type: ClusterIP
#   selector:
#     app: kafka
#   ports:
#     - protocol: TCP
#       port: 9092
#       targetPort: 9092
#       name: broker0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka0-service
spec:
  type: NodePort
  selector:
    app: kafka0
    #brokerId: "0"
  ports:
    - name: bootstrap
      protocol: TCP
      port: 9092
      targetPort: 9092 #changed from 9093
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1-service
spec:
  type: NodePort
  selector:
    app: kafka1
    #brokerId: "0"
  ports:
    - name: bootstrap
      protocol: TCP
      port: 9092
      targetPort: 9092 #changed from 9093
      nodePort: 30007

### END ###
