# LINKS FOR REFERENCE
# https://docs.ansible.com/ansible/latest/collections/openstack/cloud/server_module.html
# with AWS https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_module.html

- name: launch a compute instance
  openstack.cloud.server:
    state: present
    name: vm2Team9-demos
    region_name: KVM@TACC
    availability_zone: nova
    image: cc7a1d9a-7501-4935-b171-bb881a7d767d
    key_name: Team9
    timeout: 200
    flavor_ram: 2048
    security_groups:
      - "default"
      - "HTTP_HTTPS_INGRESS_EGRESS"
      - "SHARED-CLOUDCOMPUTING"
      - "SHARED_SSH_INGRESS"
    floating_ips:
      - 129.114.27.249
    network: "CH-822922-net"

- name: launch a compute instance
  openstack.cloud.server:
    state: present
    name: vm3Team9-demos
    region_name: KVM@TACC
    availability_zone: nova
    image: cc7a1d9a-7501-4935-b171-bb881a7d767d
    key_name: Team9
    timeout: 200
    flavor_ram: 2048
    security_groups:
      - "default"
      - "HTTP_HTTPS_INGRESS_EGRESS"
      - "SHARED-CLOUDCOMPUTING"
      - "SHARED_SSH_INGRESS"
    floating_ips:
      - 129.114.26.158
    network: "CH-822922-net"
