# LINKS FOR REFERENCE
# https://docs.ansible.com/ansible/latest/collections/openstack/cloud/server_module.html
# with AWS https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_module.html

- name: launch a compute instance
  openstack.cloud.server:
    state: present
    name: vm1
    region_name: KVM@TACC
    availability_zone: nova
    image: 01a6d6d1-e692-4e86-b776-dbb387c64958
    key_name: Team9
    timeout: 200
    flavor_ram: 2048
    security_groups: default
    auto_ip: yes

