#host: vm3
- name: Update zookeeper.connect on VM2 server.properties
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'zookeeper.connect=.*'
    line: zookeeper.connect=129.114.27.160:2181
#    line: zookeeper.connect={{ hostvars[vm2]['ansible_default_ipv4']['address'] }}:2198

- name: Update broker.id on VM2 server.properties
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'broker.id=.*'
    line: broker.id = 1

- name: Install dependencies
  become: yes
  apt:
    pkg:
      - curl
      - apt-transport-https
      - gnupg
  state: present
  update_cache: yes

- name: make script executable
  become: yes
  ansible.builtin.shell: chmod +x /home/cc/5287-A2/vagrant_ansible/couchdb_files/install_couchdb.sh

- name: run script
  become: yes
  ansible.builtin.shell: /home/cc/5287-A2/vagrant_ansible/couchdb_files/install_couchdb.sh

# if silent install, all is needed to create systemd file, start
# if no silent install, possible configuration in /opt/couchdb specifically [admin] file in local.d

# then desingate to localhost, curl commands to configure database
