#host: vm3
- name: Update zookeeper.connect on VM2 server.properties
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'zookeeper.connect=.*'
    line: zookeeper.connect=129.114.27.160:2181
#    line: zookeeper.connect={{ hostvars[vm2]['ansible_default_ipv4']['address'] }}:2198

- name: Update broker.id on VM2 server.properties
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'broker.id=.*'
    line: broker.id = 1

- name: Install couchdb
  become: yes
  apt:
    pkg:
      - curl
      - apt-transport-https
      - gnupg
  state: present
  update_cache: yes

- name: run couchdb shell script
  become: yes
