#- name: Run script
#  script: /usr/bin/python3 consumer.py
##  args:
##    chdir: "/home/cc/5287-A2/vagrant_ansible/code_files"

- name: Run Py script
  command: /usr/bin/python3 /home/cc/5287-A2/vagrant_ansible/code_files/consumer.py

#- name: Copy over consumer.service file
#  become: yes
#  copy:
#    src: /home/cc/5287-A2/vagrant_ansible/kafka_files/consumer.service
#    remote_src: yes
#    dest: /etc/systemd/system/consumer.service
#
#- name: Start consumer
#  become: yes
#  systemd:
#    name: consumer.service
#    enabled: yes
#    state: started

