---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2017
# Modified: Fall 2020
#
# This playbook is our demo master file
# The goal is to show how to have a single master file which then
# includes multiple plays according to some well-designed choreography
#
# This file is similar to the one in the AnsibleOnly_Local_and_Cloud folder
# For now I just kept one play in here but feel free to add more.
#####################################################
### Play 1: Get facts from all our VMs
#
# Here I show the use of import_tasks from child playbooks
#####################################################
# - name: "Create VMs"
#   hosts: localhost
#   connection: local
#   gather_facts: yes
#   # collections: # this is new starting with Ansible 2.9 (akin to importing package)
#   #   - openstack.cloud
#   tasks:
#     - include_tasks: tasks/create_cc_cloud_vm.yml


# - name: wait for spin up
#   hosts: localhost
#   tasks:
#   - name: wait for 45 seconds
#     wait_for:
#       timeout: 45
#     delegate_to: localhost


- name: "collect server info kubemaser"
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: get info from openstack
      openstack.cloud.server_info:
        server: team9-kubemaster-2
      register: result
    - set_fact:
        kubemaster_private: "{{ result.openstack_servers.0.private_v4 }}"
    - set_fact:
        kubemaster_public: "{{ result.openstack_servers.0.public_v4 }}"

- name: "write hosts file kubemaster"
  hosts: vm2
  tasks:
    # - name: debug
    #   debug:
    #     var: hostvars['localhost']['kubemaster_public']

    # - name: add private
    #   become: yes
    #   shell: "echo '{{ hostvars['localhost']['kubemaster_private'] }} team9-kubemaster-2 kubemaster kubeworker1' >> /etc/hosts"

    # - name: add private
    #   become: yes
    #   shell: "echo '{{ hostvars['localhost']['kubemaster_private'] }} team9-kubemaster-2 kubemaster kubeworker1' >> /etc/hosts"

    - name: verify
      become: yes
      shell: cat /etc/hosts
      register: result

    - name: debug
      debug:
        msg: "{{ result }}"


# - name: "collect server info kubeworker"
#   hosts: localhost
#   connection: local
#   gather_facts: yes
#   tasks:
#     - name: get info from openstack
#       openstack.cloud.server_info:
#         server: team9-kubeworker-2
#       register: result

#     - name: print results
#       debug:
#         var: kubemaster_info
        
        # "{{ result.openstack_servers.0.public_v4 }}"
        # msg: "{{ result.openstack_servers.0.private_v4 }}"


- name: kubernetes installation
  hosts: bothvms
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
        
    #- include_tasks: tasks/install_kubernetes.yaml
    

...

